export const devices = [
	{
		id: 1,
		name: "Living Room ESP32",
		status: "Online" as const,
		motion: "Active",
		wifi: "Excellent",
		ipAddress: "192.168.29.15",
		lastSeen: "Just now",
	},
	{
		id: 2,
		name: "Bedroom ESP32",
		status: "Online" as const,
		motion: "Idle",
		wifi: "Good",
		ipAddress: "192.168.29.18",
		lastSeen: "1 min ago",
	},
	{
		id: 3,
		name: "Garage ESP32",
		status: "Offline" as const,
		motion: "Idle",
		wifi: "Weak",
		ipAddress: "192.168.29.22",
		lastSeen: "10 min ago",
	},
	{
		id: 4,
		name: "Garden ESP32",
		status: "Online" as const,
		motion: "Active",
		wifi: "Excellent",
		ipAddress: "192.168.29.30",
		lastSeen: "Just now",
	},
];
export const summaryCards = [
	{
		id: 1,
		key: "devices",
		title: "Devices",
		value: "4",
		subtitle: "3 Online • 1 Offline",
		iconColor: "#1976d2",
	},
	{
		id: 2,
		key: "motion",
		title: "Motion",
		value: "2 Active",
		subtitle: "Last event 2 sec ago",
		iconColor: "#2e7d32",
	},
	{
		id: 3,
		key: "alerts",
		title: "Alerts",
		value: "0",
		subtitle: "No active alerts",
		iconColor: "#ed6c02",
	},
	{
		id: 4,
		key: "uptime",
		title: "Uptime",
		value: "12h 30m",
		subtitle: "99.9% Today",
		iconColor: "#7b1fa2",
	},
];
export const activities = [
	{
		id: 1,
		type: "motion",
		title: "Motion Detected",
		device: "Living Room ESP32",
		timestamp: "Just now",
	},
	{
		id: 2,
		type: "motion-end",
		title: "Motion Ended",
		device: "Living Room ESP32",
		timestamp: "2 min ago",
	},
	{
		id: 3,
		type: "device",
		title: "ESP32 Connected",
		device: "Bedroom ESP32",
		timestamp: "10 min ago",
	},
	{
		id: 4,
		type: "system",
		title: "System Started",
		device: "Dashboard",
		timestamp: "30 min ago",
	},
];
export const healthMetrics = [
	{
		id: 1,
		label: "Backend",
		value: "Online",
		status: "success",
	},
	{
		id: 2,
		label: "Database",
		value: "Connected",
		status: "success",
	},
	{
		id: 3,
		label: "Wi-Fi",
		value: "Excellent",
		status: "success",
	},
	{
		id: 4,
		label: "ESP32",
		value: "Online",
		status: "success",
	},
	{
		id: 5,
		label: "Last Sync",
		value: "2 sec ago",
		status: "info",
	},
	{
		id: 6,
		label: "Firmware",
		value: "v1.0.0",
		status: "neutral",
	},
];
